[package]
name = "odo"
version = "0.0.0"
authors = ["drakmaniso <moussault.laurent@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
